apiVersion: v1
kind: Service
metadata:
  name: trainspotter-admin-nodeport-service
  namespace: michaelmogessie
spec:
  type: NodePort
  selector:
    app.name: trainspotter-admin
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30034