apiVersion: v1
kind: Service
metadata:
  name: train-scheduler-nodeport-service
  namespace: michaelmogessie
spec:
  type: NodePort
  selector:
    app.name: train-scheduler
  ports:
    - port: 8485
      targetPort: 8485
      nodePort: 30031