apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      discovery.app: eureka
  template:
    metadata:
      labels:
        discovery.app: eureka
    spec:
      containers:
      - name: discovery-service
        image: michaelmogessie/discovery-service-docker:latest
        ports:
          - containerPort: 8484
            hostPort: 8484
      imagePullSecrets:
      - name: regcred
