apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment
  namespace: michaelmogessie
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - name: scheduler
        image: michaelmogessie/scheduler:latest
        ports:
          - containerPort: 8485
      imagePullSecrets:
      - name: regcred