apiVersion: v1
kind: Service
metadata:
  name: train-manager-nodeport-service
  namespace: michaelmogessie
spec:
  type: NodePort
  selector:
    app.name: train-manager
  ports:
    - port: 8486
      targetPort: 8486
      nodePort: 30032