apiVersion: v1
kind: Service
metadata:
  name: station-manager-nodeport-service
  namespace: michaelmogessie
spec:
  type: NodePort
  selector:
    app.name: station-manager
  ports:
    - port: 8487
      targetPort: 8487
      nodePort: 30033