apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: michaelmogessie
spec:
  type: NodePort
  selector:
    app.name: eureka
  ports:
    - port: 8483
      targetPort: 8483
      nodePort: 30030